# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = 2

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.network "private_network", ip: "192.168.56.30"
    haproxy.vm.network "forwarded_port", guest: 1936, host: 1936
    haproxy.vm.network "forwarded_port", guest: 80, host: 80

    haproxy.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end

    haproxy.vm.provision "ansible" do |ansible|
      ansible.playbook = "haproxy/playbook.yml"
    end
  end

  (0..nodes).each do |i|
    config.vm.define "cluster#{i}" do |consul|
      consul.vm.network "private_network", ip: "192.168.56.4#{i}"
      consul.vm.hostname = "cluster#{i}"

      consul.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "1024"
      end

      consul.vm.provision "ansible" do |ansible|
        ansible.playbook = "cluster/playbook.yml"
        ansible.extra_vars = {
          node_name: "cluster#{i}",
          bootstrap_expect: nodes+1,
          leader: i
        }
      end
    end
  end

  (0..nodes).each do |i|
    config.vm.define "server#{i}" do |server|
      server.vm.network "private_network", ip: "192.168.56.#{31+i}"
      server.vm.hostname = "server#{i}"

      server.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "1024"
      end

      server.vm.provision "ansible" do |ansible|
        ansible.playbook = "services/playbook.yml"
        ansible.extra_vars = {
          service_port: "606#{i}",
          service_name: "server#{i}#{i}",
          sidecar_service_port: "2200#{i}",
          sidecar_proxy_port: "1900#{i}",
          index: i
        }
      end
    end
  end
  
end
