# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.network "private_network", ip: "192.168.56.30"
  config.vm.network "forwarded_port", guest: 80, host: 6060
  config.vm.network "forwarded_port", guest: 8500, host: 8500

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2024"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.extra_vars = {
      domain: "mydomain"
    }
  end
end
