---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Add gpg key of hashicorp
    ansible.builtin.apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      state: present
  - name: Add repository hashicorp
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://apt.releases.hashicorp.com jammy main
      state: present
  - name: Install consul
    ansible.builtin.apt:
      name: consul
      state: present
      update_cache: yes
  - name: Copy server.hcl to machine
    ansible.builtin.copy:
      src: ./server.hcl
      dest: /etc/consul.d/server.hcl
  - name: System enable consul
    ansible.builtin.systemd:
      name: consul
      enabled: yes
      state: restarted

