# -*- mode: ruby -*-
# vi: set ft=ruby :
#
nodes = 2

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  (0..nodes).each do |i|
    config.vm.define "consul#{i}" do |consul|
      consul.vm.network "private_network", ip: "192.168.56.3#{i}"

      consul.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "1024"
      end

      consul.vm.provision "ansible" do |ansible|
        ansible.playbook = "consul/playbook.yml"
        ansible.extra_vars = {
          node_name: "consul#{i}",
          bootstrap_expect: nodes+1,
          leader: i
        }
      end
    end
  end
end
