# -*- mode: ruby -*-
# vi: set ft=ruby :
#
nodes = 2

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.30"
    server.vm.network "forwarded_port", guest: 80, host: 6060
    server.vm.network "forwarded_port", guest: 8500, host: 8500

    server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2024"
    end

    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "./server/playbook.yml"
    end
  end

  (1..2).each do |i|
    config.vm.define "client-#{i}" do |client|
      client.vm.hostname = "client-#{i}"
      client.vm.network "private_network", ip: "192.168.56.#{30 + i}"

      client.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "2024"
      end

      client.vm.provision "ansible" do |ansible|
        ansible.playbook = "./client/playbook.yml"
      end
    end
  end
end
